####################################
# DynamicPremium by gatogamer#6666 #
####################################

LobbyServer: "l1"

forced-lobbies-mode: true

LobbyServers:
  default:
    # Balance modes available:
    #   - LOWEST - fills servers with less users.
    #   - RANDOM - just select any server from list.
    #   - FILL - fills servers, when they are full, it'll be switched to the another one.
    balance-mode: LOWEST
    servers:
      - "l1"
      - "l2"
      - "l3"
      - "l4"
  "mc.gatogamer.gay":
    balance-mode: LOWEST
    servers:
      - "sv-l1"
      - "sv-l2"
      - "sv-l3"
      - "sv-l4"

access-only-if-player-is-premium:
  - "premium-server-1"
access-only-if-player-is-premium-message: |-
  &7&l&m----------------&b DynamicPremium &7&l&m----------------
  &7You have no access to the server because you're not premium.
  &7&l&m------------------------------------------------

AuthServers:
  - "al1"
AllowedCommands:
  - "/l"
  - "/login"
  - "/reg"
  - "/register"
SendLobbyMessage: "&a¡Enviándote al lobby!"
DeniedCommand: "&c¡Debes estar autentificado para ejecutar este comando!"
ConnectionCancelled: "&c¡La conexión fue desconectada debido a que eres premium pero no estás autentificado en Mojang!"
PremiumCommandDelay: 60000 #Millis
# This is important.
# PREMIUM (if you change your minecraft name and you have premium uuid, you will have all things that you have in the other name)
# NO_PREMIUM (if you change your minecraft name, you will loss your things, but if you're premium and you put /premium, you will not lose your things xD)
UUIDMode: PREMIUM #UUID modes available: PREMIUM, NO_PREMIUM.
Alert:
  NoPremium: "&c¡Debes ser premium para hacer esto! (esto puede ser un error por RateLimit de Mojang)"
  PlayerOnly: "&c¡Debes ser un usuario para hacer esto!"
  Enabled: "&a¡Has activado el modo premium!"
  Disabled: "&a¡Has desactivado el modo premium!"
  Cooldown: "&a¡Debes esperar para poder hacer esto!"
  Checking: |-
    &7&l&m----------------&b DynamicPremium &7&l&m----------------
    &7Hemos visto que has activado el &a/premium
    &7Debido a ello te hemos expulsado para verificar
    &7que en verdad tengas una cuenta comprada de Minecraft.
    &7Entra de nuevo y haremos la verificación.
    &7&l&m------------------------------------------------

Admin:
  Usage:
    - "&7DynamicPremium &cv${project.version} &7por gatogamer#6666"
    - ""
    - "&cAdmin commands:"
    - "&c/premiumadmin toggle <jugador> &4- &7Activas/desactivas el modo premium de otro jugador."
    - ""
  No Permission: "&c¡No tienes permiso!"
  Toggled:
    Enabled: "&a¡Has activado el modo premium a %player%!"
    Disabled: "&c¡Has desactivado el modo premium a %player%!"

# This isn't important, but...
# If you set this to DIRECT, you're forcing TO PREMIUM USERS to connect to the lobby direct. (If the lobby is down, the player will be not connected)
# If you set this to FIRST_DEFAULT, you're forcing to ALL USERS to connect to the auth server first.
# IMPORTANT: Premium users are just users that have the /premium mode enabled.
LoginType: DIRECT #Modes available: DIRECT, FIRST_DEFAULT

#Database type.
#Database types available: FLATFILE, MYSQL
DatabaseType: FLATFILE

MySQL:
  Host: "127.0.0.1"
  Port: "3306"
  Username: "root"
  Password: "password"
  Database: "DynamicPremium"
  Properties:
    - "autoReconnect=true"

Import:
  File:
    enabled: false
  FastLogin:
    enabled: false
    Host: "127.0.0.1"
    Port: "3306"
    Username: "root"
    Password: "password"
    Database: "DynamicPremium"