####################################
# DynamicPremium by gatogamer#1111 #
#          Spigot version          #
####################################

Debug: false

Authentified: "&aHas sido autentificado gracias a que eres premium."
MySQL:
  Host: "127.0.0.1"
  Port: "3306"
  Username: "root"
  Password: "password"
  Database: "DynamicPremium"
  Properties:
    - "autoReconnect=true"