####################################
# DynamicPremium by gatogamer#6666 #
#          Spigot version          #
####################################

Debug: false

#Authentified: "&aHas sido autenticado gracias a que eres premium."
Authentified: "&aYou've been authenticated because you're premium."

DatabaseType: MYSQL # Don't change to FLATFILE OTHERWISE IT'LL NOT WORK AS EXPECTED!
MySQL:
  Host: "127.0.0.1"
  Port: "3306"
  Username: "root"
  Password: "password"
  Database: "DynamicPremium"
  Properties:
    - "autoReconnect=true"