name: DynamicPremium
version: '${project.version}'
main: me.gatogamer.dynamicpremium.spigot.DynamicPremium
authors: [ gatogamer ]
description: The simplest /premium plugin ever.
website: https://gatogamer.gay
