name: DynamicPremium
version: '${project.version}'
main: im.thatneko.dynamicpremium.spigot.DynamicPremium
api-version: 1.13
authors: [ gatogamer ]
description: The simplest /premium plugin ever.
website: https://thatneko.im
